### PR TITLE
Fix inventory aspect offset + improve thaumcraft performance

### LINKED ISSUE #238: [Bug]: Tinkers' Construct Crafting Station + External Inventory Aspects Visual Bug
### Salis Arcana Version

2.0.0

### Where is the bug?

Thaumcraft 4

### Describe the bug

Checking the aspects of items when in the gui of a TiCon crafting station with an attached inventory shows the aspects of items to the far left of the cursor.

### To Reproduce

1. Place a TiCon crafting station
2. Put an inventory next to it with items inside
3. Open the crafting station
4. Press Shift with your mouse in the inventory.

### Expected Behavior

The correct aspects are shown.

### Attachments

This is showing the aspects for the wool block:
Image

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by sisyphussy**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix + performance

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/rndmorris/Salis-Arcana/issues/238

**What is the new behavior (if this is a feature change)?**

ThaumicInventoryScanner (salis arcana):
- adds `phase` checks to TickEvents.ClientTickEvents (this makes sure the event only triggers once per tick, not twice)
- dynamically register/unregister the events based on `isServerSideInstalled` (removes the need for checks on every event)

ClientTickEventsFML (thaumcraft):
- Closes https://github.com/rndmorris/Salis-Arcana/issues/238
- Rewrite the code (after testing old vs new on my pc, it runs ~3-4x faster on the cpu on average)

UtilsFX (thaumcraft):
- Replaces inefficient reflection with AT/Accessors

ParticleEngine (thaumcraft):
- Short-circuits the particle logic if there are no particles present (prevents unnecessary GL operations every render tick)
- Fewer GL operations per particle

**Does this PR introduce a breaking change?**
Adds a few `@Overwrite`s, though that shouldn't be an issue since there's absolutely no reason for another mod to inject into these methods.

**Other information**:
I've carefully tested every single one of those changes on SP, and they all worked fine. Didn't test on MP because my changes are client-side only, but `runServer` runs fine.

### CODE REVIEW

File: src/main/java/dev/rndmorris/salisarcana/mixins/late/client/fx/MixinParticleEngine.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+public class MixinParticleEngine {
+
+    @Unique
+    private boolean sa$hasParticles;
+
+    @Inject(method = "onRenderWorldLast", at = @At("HEAD"), cancellable = true)
+    private void sa$onRenderWorldLast(RenderWorldLastEvent event, CallbackInfo ci) {
+        if (!sa$hasParticles) {
+            ci.cancel();
+        }
```
Comment (Nikolay-Sitnikov) [inline src/main/java/dev/rndmorris/salisarcana/mixins/late/client/fx/MixinParticleEngine.java:24]: Please use `@WrapMethod` with an if-statement to perform this check, since that's how it is usually done in Salis Arcana.

File: src/main/resources/META-INF/salisarcana_at.cfg [hunk 2]
```diff
@@ -4,5 +4,7 @@ public net.minecraft.client.gui.Gui field_73735_i # zLevel
 public net.minecraft.client.gui.inventory.GuiContainerCreative func_146285_a(Lnet/minecraft/item/ItemStack;II)V # renderTooltip
 public net.minecraft.client.gui.inventory.GuiContainer field_147003_i # guiLeft
 public net.minecraft.client.gui.inventory.GuiContainer field_147009_r # guiTop
+public net.minecraft.client.renderer.ItemRenderer field_78454_c # equippedProgress
+public net.minecraft.client.renderer.ItemRenderer field_78451_d # prevEquippedProgress
```
Comment (Nikolay-Sitnikov) [inline src/main/resources/META-INF/salisarcana_at.cfg:8]: Why are you using both Accessors & Access Transformers?

File: src/main/java/dev/rndmorris/salisarcana/config/group/ConfigBugfixes.java [hunk 3]
```diff
@@ -245,6 +245,16 @@ public class ConfigBugfixes extends ConfigGroup {
...
 
+    public final ToggleSetting fixInventoryAspects = new ToggleSetting(
+        this,
+        "fixInventoryAspects",
+        "Fixes a bug where some gui's will render the wrong aspects when shifting over them, while also improving its performance.");
+
+    public final ToggleSetting improveTC4Performance = new ToggleSetting(
+        this,
+        "improveTC4Performance",
+        "Implements several performance-enhancers into Thaumcraft.");
```
Comment (Nikolay-Sitnikov) [inline src/main/java/dev/rndmorris/salisarcana/config/group/ConfigBugfixes.java:256]: Details about what classes it modifies and in which ways would be appreciated. (Also, this config might arguably go into thaumcraft-config, but I'd want Morris's confirmation on that.)

File: src/main/java/dev/rndmorris/salisarcana/mixins/late/client/fx/MixinParticleEngine.java [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+    private void sa$removeUselessGlPop() {}
+
+    @Inject(method = "addEffect", at = @At("TAIL"))
+    private void sa$addEffect(CallbackInfo ci) {
+        sa$hasParticles = true;
+    }
+
+    @Inject(method = "updateParticles", at = @At("HEAD"), cancellable = true)
+    private void sa$shortCircuitUpdate(CallbackInfo ci) {
+        if (!sa$hasParticles) {
```
Comment (Nikolay-Sitnikov) [inline src/main/java/dev/rndmorris/salisarcana/mixins/late/client/fx/MixinParticleEngine.java:44]: Same thing, use `@WrapMethod`. (Unless you have a good reason *not* to use it?)

Using `@WrapMethod` means that if someone else mixes into this method with an `@Inject` to HEAD, there would be no chance of their code triggering accidentally.

File: src/main/java/dev/rndmorris/salisarcana/mixins/late/client/lib/MixinUtilsFX.java [hunk 5]
```diff
@@ -0,0 +1,109 @@
...
+
+    static {
+        // this can also be done via accessors, makes no difference though.
+        ResourceLocation location;
+        try {
+            Field f;
+            try {
+                f = EffectRenderer.class.getDeclaredField("field_110737_b");
+            } catch (Exception e) {
+                f = EffectRenderer.class.getDeclaredField("particleTextures");
```
Comment (Nikolay-Sitnikov) [inline src/main/java/dev/rndmorris/salisarcana/mixins/late/client/lib/MixinUtilsFX.java:100]: Use the `ObfuscationInfo` enum instead of testing each name separately.

File: src/main/java/dev/rndmorris/salisarcana/config/group/ConfigBugfixes.java [hunk 6]
```diff
@@ -245,6 +245,16 @@ public class ConfigBugfixes extends ConfigGroup {
         "clampWandOverlayVis",
         "Prevents the \"Vis in Wand\" GUI when the wand is held from showing impossible bars when the wand holds impossible amounts of vis.");
 
+    public final ToggleSetting fixInventoryAspects = new ToggleSetting(
+        this,
+        "fixInventoryAspects",
+        "Fixes a bug where some gui's will render the wrong aspects when shifting over them, while also improving its performance.");
```
Comment (Nikolay-Sitnikov) [inline src/main/java/dev/rndmorris/salisarcana/config/group/ConfigBugfixes.java:251]:
```suggestion
        "Some GUIs will no longer render the wrong aspects when shifting over a slot. Also improves the performance of this overlay.");
```

**Review by Nikolay-Sitnikov — CHANGES_REQUESTED** [review]
You also need to add entries to the `.md` files about these configs.

(Feel free to just copy-paste the setting description.)

File: src/main/java/dev/rndmorris/salisarcana/config/group/ConfigBugfixes.java (hunk 3 above)
Comment (sisyphussy) [reply src/main/java/dev/rndmorris/salisarcana/config/group/ConfigBugfixes.java:256]: I was planning on adding more stuff to it later on, so i thought that a more abstract name would be better. Though the changes that are in right now + that I plan on adding are all rendering-based, so i could say that.

Also, i think thaumcraft config would be better now that you mention it, yeah.

File: src/main/resources/META-INF/salisarcana_at.cfg (hunk 2 above)
Comment (sisyphussy) [reply src/main/resources/META-INF/salisarcana_at.cfg:8]: was trying it in gtnh

**Review by Nikolay-Sitnikov — DISMISSED** [review]

File: src/main/java/dev/rndmorris/salisarcana/client/ThaumicInventoryScanner.java [hunk 7]
```diff
@@ -78,18 +75,35 @@ static int getScanTicks() {
...
      * accordingly
      **/
 
     public void init(FMLInitializationEvent event) {
+        instance = this;
         effectRenderer = new ClientTickEventsFML();
     }
 
     public void postInit(FMLPostInitializationEvent event) {
         thaumometer = GameRegistry.findItem("Thaumcraft", "ItemThaumometer");
```
[the remark this answers is not in the document]
Comment (Nikolay-Sitnikov) [reply src/main/java/dev/rndmorris/salisarcana/client/ThaumicInventoryScanner.java:105]: (Specifically, replace all usages of `thaumometer` with `ConfigItems.itemThaumometer`.)

File: src/main/java/dev/rndmorris/salisarcana/client/ThaumicInventoryScanner.java [hunk 8]
```diff
@@ -241,60 +255,55 @@ public void onDrawScreen(GuiScreenEvent.DrawScreenEvent.Post event) {
...
+            final int y = mouseY + 7 - 33;
+            final float zLevel = UtilsFX.getGuiZLevel(gui);
+
+            int x = mouseX + 17;
+            for (Aspect tag : tags.getAspectsSortedAmount()) {
+                if (tag != null) {
+
+                    UtilsFX.bindTexture("textures/aspects/_back.png");
+                    GL11.glPushMatrix();
+                    GL11.glEnable(GL11.GL_BLEND);
```
Comment (Nikolay-Sitnikov) [inline src/main/java/dev/rndmorris/salisarcana/client/ThaumicInventoryScanner.java]: This call should probably be moved outside the loop.

File: src/main/java/dev/rndmorris/salisarcana/mixins/late/thaumcraft/client/lib/MixinClientTickEventsFML_SlotAspectPopup.java [hunk 9]
```diff
@@ -0,0 +1,103 @@
...
+                final int y = mouseY + 7 - 33;
+                final float zLevel = UtilsFX.getGuiZLevel(gui);
+
+                int x = mouseX + 17;
+                for (Aspect tag : tags.getAspectsSortedAmount()) {
+                    if (tag != null) {
+
+                        UtilsFX.bindTexture("textures/aspects/_back.png");
+                        GL11.glPushMatrix();
+                        GL11.glEnable(GL11.GL_BLEND);
```
Comment (Nikolay-Sitnikov) [inline src/main/java/dev/rndmorris/salisarcana/mixins/late/thaumcraft/client/lib/MixinClientTickEventsFML_SlotAspectPopup.java]: Same here.

**Review by Midnight145 — DISMISSED** [review]
Looks good, thanks a lot!

Sorry for the delay, I misunderstood the status of this and thought it was still waiting for changes 😅

**Review by Midnight145 — APPROVED** [review]
