### PR TITLE
notice if tcinventoryscan is independently installed

### LINKED ISSUE #95: Duplicate Inventory Scanning Tooltip
**Describe the bug**
Duplicate inventory scanning tooltip when tcinventoryscan is also present

**To Reproduce**
1. Have both salis arcana and tcinventoryscan installed
2. Look at the thaumometer

**Expected behavior**
The tooltip only shows up once. Maybe send a message to remove tcinventoryscan if it finds that it is also installed?

**Screenshots**

Image

**Additional context**
Maybe also add something that says about scanning inventory blocks with new items inside.

### PR DESCRIPTION
**Pull request by Midnight145**
closes #95 

image

### CODE REVIEW

File: src/main/java/dev/rndmorris/salisarcana/notifications/StartupNotifications.java [hunk 1]
```diff
@@ -2,23 +2,31 @@
...
 
 public class StartupNotifications {
 
-    private boolean noticeSent = false;
+    private boolean deprecationNoticeSent = false;
+
+    private boolean tcInventoryScanNoticeSent = !Loader.isModLoaded("tcinventoryscan");
 
     @SubscribeEvent
     public void onLogin(PlayerEvent.PlayerLoggedInEvent event) {
```
Comment (rndmorris) [inline src/main/java/dev/rndmorris/salisarcana/notifications/StartupNotifications.java:17]: In this case, since we now have multiple notices, I think it would make sense to put each on in their own method, called from here. e.g.

```java
public void onLogin(...) {
    sendDeprecationNotice(event);
    sendTcInventoryScanNotice(event);
}
```

**Review by rndmorris — CHANGES_REQUESTED** [review]

**Review by rndmorris — APPROVED** [review]
