### PR TITLE
Correctly sync aspect updates to the client when `/forget-aspect` is used in multi-player

### LINKED ISSUE #271: [Bug]: forget aspect commands only forget server-side, not client-side
### Salis Arcana Version

2.1.0

### Where is the bug?

Salis Arcana

### Describe the bug

i oopsied it and forgetting aspects dont work

### To Reproduce

1. run forget aspect command
2. observe that blocks in the world still have discovered aspects

### Expected Behavior

aspects to be forgotten properly

### Attachments

_No response_

### Additional Context

whoops, my bad

### PR DESCRIPTION
**Pull request by Midnight145**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
bugfix

**What is the current behavior?** (You can also link to an open issue here)
#271 

**What is the new behavior (if this is a feature change)?**
closes #271

**Does this PR introduce a breaking change?**
no

**Other information**:
draft pr because untested, should work though

### CODE REVIEW

**Review by rndmorris — CHANGES_REQUESTED** [review]
As mentioned in the issue, this is a bit backwards to what we actually need. The command runs server-side so the client needs informed of the updates, not the server.

**Comment by rndmorris** [comment]
Does not appear to work after the last round of testing, the client still needed to relog to get updated.

**Review by rndmorris — CHANGES_REQUESTED** [review]
Pulled the latest changes. Ran `/tc aspect @p herba 1` followed by `/forget-aspect --forget --aspect herba`. Herba was added, but still had to relog for the forgetting to apply.

**Comment by Midnight145** [comment]
why am i small brain

File: src/main/java/dev/rndmorris/salisarcana/network/MessageForgetAspects.java
Comment (rndmorris) [inline src/main/java/dev/rndmorris/salisarcana/network/MessageForgetAspects.java:1]: Non-blocking: we can probably safely merge these into one packet with an `action` byte to determine whether to reset or forget.

**Review by rndmorris — APPROVED** [review]
Behaves as expected now

**Review by rndmorris — CHANGES_REQUESTED** [review]
### Testing
:heavy_check_mark: Reset individual aspects
:heavy_check_mark: Reset all aspects
:heavy_check_mark: Forget all aspects
:x: Forget individual aspects does not work

File: src/main/java/dev/rndmorris/salisarcana/common/commands/ForgetAspectCommand.java [hunk 1]
```diff
@@ -16,12 +16,17 @@
...
 import dev.rndmorris.salisarcana.config.SalisConfig;
+import dev.rndmorris.salisarcana.network.MessageResetAspects;
+import dev.rndmorris.salisarcana.network.NetworkHandler;
 import thaumcraft.api.aspects.Aspect;
 import thaumcraft.api.aspects.AspectList;
 import thaumcraft.common.Thaumcraft;
 
 public class ForgetAspectCommand extends ArcanaCommandBase<ForgetAspectCommand.Arguments> {
 
+    public static final byte RESET_ACTION = (byte) 0;
```
Comment (rndmorris) [inline src/main/java/dev/rndmorris/salisarcana/common/commands/ForgetAspectCommand.java:27]: I intended to suggest putting these in the message class, not the command. It doesn't make much sense for the message class to refer to the command.

**Review by rndmorris — CHANGES_REQUESTED** [review]
### Testing
:heavy_check_mark: Reset individual aspects
:heavy_check_mark: Reset all aspects
:heavy_check_mark: Forget all aspects
:heavy_check_mark: Forget individual aspects

**Comment by Midnight145** [comment]
Also renamed the packet to MessageForgetAspects to be in line with the command

**Review by rndmorris — APPROVED** [review]
