### PR TITLE
move forget aspect functionality into new command

### LINKED ISSUE #183: [Bug]: forget-scanned --aspects can forget primary aspects
### Salis Arcana Version

latest commit

### Where is the bug?

Salis Arcana

### Describe the bug

You can completely forget primary aspects which is normally impossible

### To Reproduce

run /forget-scanned --aspects aer (or any other primary aspect)

### Expected Behavior

either nothing or aspect count to be set to zero

### Attachments

_No response_

### Additional Context

mental note for me, make --all not mutually exclusive with --aspects

### PR DESCRIPTION
**Pull request by Midnight145**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This moves the current aspect modification from the forget-scanned command to a new forget-aspect command. Additionally, it allows you to reset the count of research points for an aspect to 1 instead of forgetting entirely if you wish.

**What is the current behavior?** (You can also link to an open issue here)
It is all lumped into one command

**What is the new behavior (if this is a feature change)?**
It is no longer all one command, and also has the new research point feature

**Does this PR introduce a breaking change?**
No

**Other information**:
closes #183 
first part was unnecessary as what I thought the bug was, was due to (now removed) behavior I had introduced, and second part is implemented here.

### CODE REVIEW

File: src/main/java/dev/rndmorris/salisarcana/common/commands/ForgetAspectCommand.java [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+
+    @Override
+    protected void process(ICommandSender sender, Arguments arguments, String[] args) {
+        if (arguments.targetPlayer == null) {
+            arguments.targetPlayer = getCommandSenderAsPlayer(sender);
+        }
+        final var playerKnowledge = Thaumcraft.proxy.getPlayerKnowledge();
+        int removedCount = 0;
+        final var playerAspects = playerKnowledge.aspectsDiscovered.get(arguments.targetPlayer.getCommandSenderName());
+        if (playerAspects != null) {
```
Comment (rndmorris) [inline src/main/java/dev/rndmorris/salisarcana/common/commands/ForgetAspectCommand.java:51]: There should probably be a different error message if neither `forget` or `reset` are selected, since the command requires one of them

File: src/main/resources/assets/salisarcana/lang/en_US.lang [hunk 2]
```diff
@@ -40,12 +40,21 @@ salisarcana:command.forget-scanned.args.inventory=§7[--inventory]§r Reset all
...
 
 salisarcana:command.forget-scanned.success=§9Success:§r %d entries were removed from %s's scan lists.
 salisarcana:command.forget-scanned.failure=§cFailure:§r There was nothing to remove from %s's scan lists.
 
+salisarcana:command.forget-aspect.desc=Forget or reset aspects from a player's knowledge.
+salisarcana:command.forget-aspect.usage=§7/salisarcana-forget-aspect §7[--player §7<username>] §7[--reset] §7[--forget] §7[--aspect <...>] §7[--all] §r
+salisarcana:command.forget-aspect.args.player=§7[--player §7<username>]§r Specify the player whose aspects will be altered. If not provided, defaults to the player executing this command.
+salisarcana:command.forget-aspect.args.reset=§7[--reset]§r Reset the amount of research aspects the player has to 1. Mutually exclusive with §7forget§r.
+salisarcana:command.forget-aspect.args.forget=§7[--forget]§r Forget the aspect, requiring it to be rediscovered. Mutually exclusive with §7reset§r.
+salisarcana:command.forget-aspect.args.aspect=§7[--aspects §7<aspect[ §7aspect[ §7...]]]§r Specify the aspect(s) to reset or forget. Mutually exclusive with §7all§r.
```
Comment (rndmorris) [inline src/main/resources/assets/salisarcana/lang/en_US.lang:52]: Typo: `--aspects` should be `--aspect`

**Review by rndmorris — CHANGES_REQUESTED** [review]
Couple minor things, otherwise it works as expected.

**Review by rndmorris — APPROVED** [review]
