### PR TITLE
Clear new research highlight on Thaumonomicon right-click close

### LINKED ISSUE #329: [Bug]: When closing Thaumonomicon using right click, new researches mark is not cleared
### Salis Arcana Version

1.1.25

### Where is the bug?

Salis Arcana

### Describe the bug

When i close Thaumonomicon with right click, notifications/marks near new researches is not cleared, only happens when you close it as normal, using Esc.

### To Reproduce

1. Get new research
2. Open book, notice the new research mark
3. Close the book using right click
4. Open again, mark is not cleared

### Expected Behavior

New researches mark as seen

### Attachments

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Midnight145**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
bugfix

**What is the current behavior?** (You can also link to an open issue here)
#329 

**What is the new behavior (if this is a feature change)?**
closes #329 

**Does this PR introduce a breaking change?**
no

**Other information**:
n/a

### CODE REVIEW

File: src/main/java/dev/rndmorris/salisarcana/mixins/late/gui/MixinGuiResearchBrowser_RightClickClose.java [hunk 1]
```diff
@@ -25,6 +27,9 @@ public class MixinGuiResearchBrowser_RightClickClose extends GuiScreen {
     @Shadow(remap = false)
     protected double guiMapY;
 
+    @Shadow(remap = false)
+    public static ArrayList<String> highlightedItem;
```
Comment (Nikolay-Sitnikov) [inline src/main/java/dev/rndmorris/salisarcana/mixins/late/gui/MixinGuiResearchBrowser_RightClickClose.java:31]: You don't seem to be using this shadowed field.

**Review by Nikolay-Sitnikov — DISMISSED** [review]

File: src/main/java/dev/rndmorris/salisarcana/mixins/late/gui/MixinGuiResearchBrowser_RightClickClose.java (hunk 1 above)
Comment (Nikolay-Sitnikov) [reply src/main/java/dev/rndmorris/salisarcana/mixins/late/gui/MixinGuiResearchBrowser_RightClickClose.java:31]: ...Since when do I have write access? It shouldn't disable merging.

**Review by rndmorris — APPROVED** [review]
