### PR TITLE
Make upgraded foci with a different casting vis cost than the base focus spend the correct cost.

### LINKED ISSUE #269: [Bug]: Fix vis cost of upgraded foci
### Salis Arcana Version

2.1.0

### Where is the bug?

Thaumcraft 4

### Describe the bug

Giving wand foci certain upgrades is supposed to also affect their vis cost. For example:
- Chain Lightning adds a small aqua Cost to the Shock Focus
- Fireball adds a small perditio cost to the Fire Focus
- Ice Boulder adds a small terra cost to the Frost Focus

This is reflected in their tooltips, except... it's not real? You can spam as much chain-lighting as you want but the wand never seems to consume aqua vis.

### To Reproduce

1. Upgrade a Fire Focus with Fireball
2. Observe the tooltip now claims a cost of 0.66 ignis vis and 0.33 periditio vis
3. Shoot fireballs
4. Only ignis vis is consumed

### Expected Behavior

1. Upgrade a Fire Focus with Fireball
2. Observe the tooltip now claims a cost of 0.66 ignis vis and 0.33 periditio vis
3. Shoot fireballs
4. Both ignis and perditio vis is consumed

You could of course change the tooltip instead but judging by Azanor's code, the original intention definitely seems to be that the vis cost does in fact change.

### Attachments

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Nikolay-Sitnikov**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix - causes upgraded foci to spend the correct vis cost.

**What is the current behavior?** (You can also link to an open issue here)
Closes #269

**What is the new behavior (if this is a feature change)?**
Foci will check the focus item in order to determine present upgrades instead of checking the wand item (which cannot have focus upgrade NBT tags.)

**Does this PR introduce a breaking change?**
No

### CODE REVIEW

File: src/main/java/dev/rndmorris/salisarcana/mixins/late/api/MixinItemFocusBasic_WandUpgradeLevel.java [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+import thaumcraft.api.wands.ItemFocusBasic;
+import thaumcraft.common.items.wands.ItemWandCasting;
+
+@Mixin(ItemFocusBasic.class)
+public class MixinItemFocusBasic_WandUpgradeLevel {
+
+    @WrapMethod(method = "getAppliedUpgrades", remap = false)
+    public short[] unwrapWandItem(ItemStack focusStack, Operation<short[]> original) {
+        if (focusStack.getItem() instanceof ItemWandCasting wand) {
+            focusStack = wand.getFocusItem(focusStack);
```
Comment (Midnight145) [inline src/main/java/dev/rndmorris/salisarcana/mixins/late/api/MixinItemFocusBasic_WandUpgradeLevel.java:19]: sanity checking myself, focusStack can't be null here, right? Thaum doesn't do any later checks before dereferencing it, so we need to guarantee it can't be.

Comment (Nikolay-Sitnikov) [reply src/main/java/dev/rndmorris/salisarcana/mixins/late/api/MixinItemFocusBasic_WandUpgradeLevel.java:19]: Well, the original function will also cause a `NullReferenceException` if you try to pass it a `null`, and this function shouldn't ever get called on a wand without a focus. I can add a sanity check for that, if you wish?

Comment (Midnight145) [reply src/main/java/dev/rndmorris/salisarcana/mixins/late/api/MixinItemFocusBasic_WandUpgradeLevel.java:19]: I assumed it wouldn't ever get called if the wand didn't have a focus, but intellij wasn't looking up function calls in Thaum's code as well for some reason, so I couldn't verify myself. Should be good then.

**Review by Midnight145 — DISMISSED** [review]

**Review by Midnight145 — APPROVED** [review]
